package it.polimi.ingsw.client.controller;

public enum ClientState {
    START_SCREEN,
    DISCARD_INITIAL_LEADER_CARDS,
    NICK_NAME,
    WAIT_FOR_OTHER_PLAYERS,
    GAME_ENTRANCE,
    CHOOSE_MAIN_ACTION,
    TAKE_FROM_MARKET,
    ACTIVATE_PRODUCTION,
    BUY_DEV_CARD,
    REALLOCATE_RESOURCES,
    //VATICAN_STATUS_UPDATE


}
